config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  mount Sidekiq::Web => '/sidekiq'
  resources :carts, only: [:show]
  resources :items, only: [:create, :show, :destroy] do
    collection do
      post :undo
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :items
  has_many :products, through: :items

  def total_price
    total = 0
    items.map { |item| total += item.product.price * item.quantity }
    total
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :cart

  def amount
    self.amount = cart.total_price
  end

  def pay(payment_method)

  end
end

app/models/product.rb
class Product < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = Cart.find(params[:id])
  end

  private

  def cart_parameters
    params.require(:cart).permit(:id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @item = Item.new(item_parameters)
    item_json = @item.serializable_hash.to_json
    item_job = CartWorker.perform_in(10.seconds, item_json)
    flash[:item_job] = item_job
    redirect_to root_url
  end

  def destroy
    @item = Item.find(item_parameters[:id])
    @item.destroy
    redirect_to cart_path(1)
  end

  def undo
    ss = Sidekiq::ScheduledSet.new
    jobs = ss.select { |job| job.jid == item_parameters[:item_job] }
    jobs.each(&:delete)
    redirect_to root_path
  end

  private

  def item_parameters
    params.permit(:id, :quantity, :product_id, :item_job)
        .merge(cart_id: 1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/show.html.erb
<h1>My Cart</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price (US$)</th>
    <th>Quantity</th>
    <th>Actions</th>
  </tr>

  <% @cart.items.map do |i| %>
    <tr>
      <td><%= i.product.name %></td>
      <td><%= i.product.description %></td>
      <td>US$ <%= format("%.2f", i.product.price) %></td>
      <td><%= i.quantity %></td>
      <td>
        <%= form_tag item_path(i), method: :delete do %>
          <%= submit_tag 'Remove' %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<br><br>
<table>
  <tr>
    <td>Total</td>
    <td>US$ <%= @cart.total_price %></td>
  </tr>
</table>

<%= link_to 'Buy more products', root_url %>

app/views/home/index.html.erb
<h1>List of all Products</h1>
<% if flash[:item_job] %>
  <h3>
    <%= form_tag undo_items_path(item_job: flash[:item_job]), method: :post do %>
      <%= submit_tag 'Undo the shopping' %>
    <% end %>
  </h3>
<% end %>
<h3>

</h3>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price (US$)</th>
    <th>Quantity</th>
  </tr>
  <% Product.all.each do |p| %>
    <tr>
      <td><%= p.name %></td>
      <td><%= p.description %></td>
      <td>US$ <%= format("%.2f", p.price) %></td>
      <td>
        <%= form_tag items_path, method: :post do %>
          <%= number_field_tag :quantity, 0, min: 0 %>
          <%= submit_tag 'Add to cart' %>
          <%= hidden_field_tag :product_id, p.id %>
        <% end %>
      </td>
    </tr>
  <% end %>
  <tfoot>
  <tr>
    <td><%= link_to 'Go to my cart', cart_path(Cart.first) %></td>
  </tr>
  </tfoot>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioSti1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>